### ISSUE TITLE
Image not working

### ISSUE THREAD

**Issue by brneor** [milescsmith/jupyter-perl#1]
Hi! Even though the image on Docker Hub is working properly,  the image built from this Dockerfile don't. When I create a new perl notebook, I keep seeing errors like `Nudge: attempt 10 on kernel a97fe0b8-3484-415b-8255-2af884d16988` on console and nothing is interpreted on Jupyter Notebook. 

Is it possible that this repo is out of date? Thanks in advance.

**Comment by zmughal** [comment]
It should build now with the release of Devel::IPerl v0.010. I had to update the Jupyter message protocol.

**Comment by brneor** [comment]
It's working now indeed. Thank you!
